#ifndef SIMUCOPTER_BRIDGE_SIMUCOPTER_ARDUPILOT_H
#define SIMUCOPTER_BRIDGE_SIMUCOPTER_ARDUPILOT_H

#include "bridge/bridge.h"
#include "simucopter.h"

#endif //SIMUCOPTER_BRIDGE_SIMUCOPTER_ARDUPILOT_H
